CREATE TABLE T_USER (
   USERID      VARCHAR(50) NOT NULL,
   PASSWORD    VARCHAR(100) NOT NULL,
   USERNAME    VARCHAR(100) NOT NULL,
   PRIMARY KEY (USERID)
);


CREATE TABLE T_ROLE (
   USERID      VARCHAR(50) NOT NULL,
   ROLE        VARCHAR(100) NOT NULL,
   PRIMARY KEY (USERID,ROLE)
);


INSERT INTO T_USER VALUES ('awi','awi123','Awiyanto');
INSERT INTO T_USER VALUES ('budi','budi123','Budi');
INSERT INTO T_USER VALUES ('apiclient','apiclient123','Api Client');

INSERT INTO T_ROLE VALUES ('awi','ROLE_ADMIN');
INSERT INTO T_ROLE VALUES ('budi','ROLE_USER');
INSERT INTO T_ROLE VALUES ('apiclient','ROLE_APICLIENT');
